### ISSUE TITLE
Bottom navigation bar - UI

### ISSUE THREAD

**Issue by gabrielbmoro** [theolm/instagram-clone#7]
![image](https://github.com/theolm/instagram-clone/assets/9204234/171ee38e-9534-4498-ae2b-d4c29be8a698)

https://www.figma.com/file/cZD992LqUS9kO79KNAdbYP/Instagram-UI-Screens-(Community)?type=design&node-id=0-1724&mode=design&t=ZG9HlqMQl9a4Accc-4

**Comment by ricardo7martins** [comment]
Quero pegar essa, se possível

**Comment by gabrielbmoro** [comment]
@ricardo7martins already implemented, so I am closing that.
